name: client
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  google_sign_in: ^4.4.4
  flutter_facebook_login: ^3.0.0
  flutter_screenutil: ^1.1.0
  device_preview: ^0.4.4
  equatable: ^1.1.1
  flutter_modular: ^1.1.2
  stacked: 1.3.4
  responsive_builder: ^0.1.5
  form_field_validator: ^1.0.1
  flushbar: ^1.10.4
  responsive_framework: ^0.0.7
  intl:
  uuid: ^2.1.0
  adobe_xd: ^0.1.4
  latlong: ^0.6.1
  flutter_map: ^0.9.0
  synchronized: ^2.2.0
  badges: ^1.1.1




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf 

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

